### ISSUE TITLE
将vbc和rna提币到gencechain后vbc和rna现在无法交易包括抵押提币操作

### ISSUE THREAD

**Issue by wangjigao123** [genechain-io/geneth#1]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by genechain-dev** [comment]
This is not related to geneth. Please ask a question on https://forum.dera.finance/ for helps on tokens or dapps.

**Comment by ydh7988wx** [comment]
基因链什么时候开网，雷达支付什么时候开网，是否可以提供一点消息？？？？？？
